/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LocationInfo } from "./interfaces/type";
export { LocationInfo } from "./interfaces/type";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyHeader {
        "email": string;
        "label": string;
        "name": string;
        "phone": string;
        "website": string;
    }
    interface MyProfile {
        "image": string;
        "location": LocationInfo;
        "name": string;
        "summary": string;
    }
    interface MyResume {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {
    }
    var HTMLMyHeaderElement: {
        prototype: HTMLMyHeaderElement;
        new (): HTMLMyHeaderElement;
    };
    interface HTMLMyProfileElement extends Components.MyProfile, HTMLStencilElement {
    }
    var HTMLMyProfileElement: {
        prototype: HTMLMyProfileElement;
        new (): HTMLMyProfileElement;
    };
    interface HTMLMyResumeElement extends Components.MyResume, HTMLStencilElement {
    }
    var HTMLMyResumeElement: {
        prototype: HTMLMyResumeElement;
        new (): HTMLMyResumeElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-header": HTMLMyHeaderElement;
        "my-profile": HTMLMyProfileElement;
        "my-resume": HTMLMyResumeElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyHeader {
        "email"?: string;
        "label"?: string;
        "name"?: string;
        "phone"?: string;
        "website"?: string;
    }
    interface MyProfile {
        "image"?: string;
        "location"?: LocationInfo;
        "name"?: string;
        "summary"?: string;
    }
    interface MyResume {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-header": MyHeader;
        "my-profile": MyProfile;
        "my-resume": MyResume;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-header": LocalJSX.MyHeader & JSXBase.HTMLAttributes<HTMLMyHeaderElement>;
            "my-profile": LocalJSX.MyProfile & JSXBase.HTMLAttributes<HTMLMyProfileElement>;
            "my-resume": LocalJSX.MyResume & JSXBase.HTMLAttributes<HTMLMyResumeElement>;
        }
    }
}
